services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: vakantie-drohnecken-2026:latest
    container_name: vakantie-drohnecken-2026
    restart: unless-stopped
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
